name: Continuous Integration

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

env:
  pat_token: ${{ secrets.REPO_ACCESS_TOKEN }}
  secret_name: QBO_TESTS_REFRESH_TOKENS
  QBO_TESTS_REFRESH_TOKENS: ${{ secrets.QBO_TESTS_REFRESH_TOKENS }}

jobs:
  pytest:
    runs-on: ubuntu-latest
    environment: CI Environment
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          echo "secret_body=sampletest" >> $GITHUB_ENV
          echo "secret_body=$secret_body"
      - name: gh auth login
        shell: bash
        run: gh auth login --with-token <<< $pat_token
      - name: gh update refresh token
        shell: bash
        run: |
          echo "secret_body"
          echo $secret_body | sed 's/./& /g'
          echo "before updating"
          echo ${{ secrets.QBO_TESTS_REFRESH_TOKENS }} | sed 's/./& /g'
          repository='${{ github.repository }}'
          gh secret set "$secret_name" --body "$secret_body" --repo $repository
          echo "after updating"
          echo ${{ secrets.QBO_TESTS_REFRESH_TOKENS }} | sed 's/./& /g'
      